cmake_minimum_required(VERSION 3.20)
include(set_compiler_options)
set(module_source_files
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/algorithm/clamp.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/algorithm/compare.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/algorithm/sort/bubble_sort.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/algorithm/sort/insertion_sort.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/array/array_view.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/array/array_view_vector.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/bitset/bit_iterator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/bitset/bitset_adapter.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/bitset/bitset_utilities.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/bitset/dynamic_bitset.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/bitset/enum_bitset.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/bitset/fixed_bitset.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/branchless/int_if.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/branchless/swap_if.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/concepts/callable.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/constexpr/hex_to_dec.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/constexpr/to_lower.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/delegate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/exception/call_and_rethrow.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/exception/checked_cast.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/exception/print_exception.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/exception/throw_if_failed.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/frame_rate_counter.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/functional/call_for_each_arg.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/functional/wrap.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/guid.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/guid_fmtlib.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/math/constants.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/math/float_range.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/math/int_range.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/math/math.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/math/matrix.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/math/surface_points.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/observable.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/pointer/intrusive_ptr.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/preprocessor/empty_bases.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/preprocessor/expot_import.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/preprocessor/stringify.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/ranges/array_indices2d.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/size.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/all_types_match_condition.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/any_type_match_condition.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/apply_if.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/fwd_decl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/is_specialization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/overload.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/pure_same_types.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/signature.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/static_for.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/string_literal.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/tagged_identifier.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/tagged_type_id.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/types_list.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/values_list.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/worst_qualifiers.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/template/worst_reference.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/public/edt/time/measure_time.hpp)
add_library(edt INTERFACE ${module_source_files})
set_generic_compiler_options(edt INTERFACE)
target_include_directories(edt INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/code/public)
target_include_directories(edt INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/code/private)
