cmake_minimum_required(VERSION 3.20)
include(set_compiler_options)
set(module_source_files
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/algorithm/clamp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/algorithm/clamp_exhaustive.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/algorithm/compare.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/algorithm/sort/bubble_sort.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/algorithm/sort/insertion_sort.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/algorithm/sort/sort_cases.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/aliases.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/bit_iterator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/bitset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/bitset_adapter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/bitset_adapter_array.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/bitset_fuzz.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/bitset_utilities.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/dynamic_bitset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/enum_bitset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/fixed_bitset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/bitset/fixed_bitset_constexpr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/branchless/int_if.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/branchless/swap_if.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/callbacks_edge_cases.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/constexpr/hex_to_dec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/delegate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/exception/call_and_rethrow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/exception/checked_cast.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/exception/checked_cast_matrix.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/exception/print_exception.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/exception/throw_if_failed.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/frame_rate_counter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/functional/functional.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/functional/on_scope_leave.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/guid/guid.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/guid/guid_format.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/guid/guid_parse.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/math/math_test.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/math/matrix_edge_cases.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/math/matrix_test.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/math/ranges.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/math/rotator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/math/transform.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/observable.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/pointer/intrusive_ptr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/public_headers.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/ranges/array_indices2d.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/size.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/string/char_util.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/apply_if.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/is_specialization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/member_offset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/overload.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/pure_same_types.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/signature.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/static_for.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/string_literal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/tagged_identifier.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/types_list.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/values_list.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/worst_qualifiers.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/template/worst_reference.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/test_tools.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/threading/batch_thread_pool.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/code/private/time/measure_time.cpp)
add_executable(edt_tests ${module_source_files})
set_generic_compiler_options(edt_tests PRIVATE)
target_link_libraries(edt_tests PRIVATE edt
                                        gtest_main)
target_include_directories(edt_tests PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/code/public)
target_include_directories(edt_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/code/private)
enable_testing()
include(GoogleTest)
gtest_discover_tests(edt_tests)
